# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O9ModdhdIZ1tn1jdcHDWILj3XbL2WIU6
"""

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print("\n")

zeros=np.zeros((2,2))

ones=ones =np.ones((2,2))

const=np.full((2,2), 5)

iden = np.eye(2)

rndom= np.random.random((2,2))
print(zeros)
print("\n")
print(ones)
print("\n")
print(const)
print("\n")
print(iden)
print("\n")
print(rndom)
print("\n")

zerod = np.array(1)
print(zerod)
print("\n")

oned = np.array([1,1])
print(oned)
print("\n")

twod=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(twod)
print("\n")

threed = np.array([[2,3,4], [5,6,7], [9,10,11]])
print(threed)
print("\n")

multid = np.array([1,2,3,4,5], ndmin=3)
print(multid)

print(zerod.ndim)
print(oned.ndim)
print(twod.ndim)
print(threed.ndim)
print(multid.ndim)

sample = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(0, len(sample)):
   print(i, end=" ")
print("\n")

sample[1]=100
print(sample)
print("\n")

sample=np.delete(sample, 2)
print(sample)

x = list(range(0,20000,5))
ss_array=np.array(x)
res = np.where(ss_array==5500)
print(res)

print(ss_array[1100])

sort=np.array([1,2,3,4,5,6,7,8,9])
x=np.sort(sort)
print(x)

a=np.array([[1,2,3]], dtype=np.int64)
b=np.array([[4,5,6]], dtype=np.int64)

add=np.add(a,b)
print(add)
print("\n")

subtract=np.subtract(a,b)
print(subtract)
print("\n")

mltp=np.multiply(a,b)
print(mltp)
print("\n")

dvd=np.divide(a,b)
print(dvd)
print("\n")

sqrt=np.sqrt(a)
print(sqrt)
print("\n")

x=np.array([[1,2,3], [1,2,3], [6,7,8]])
transpose=np.transpose(x)
print(x)
print("\n")
print(transpose)