# -*- coding: utf-8 -*-
"""Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E1_XPTbFlCbj_fxK7cIn3YFGWzqmQyL3
"""

Aimport array as myarray
arr=myarray.array("i" , [1,2,3])
arr1=myarray.array("d", [1.0,2.1, 2.4, 25, 2.6])
arr2=myarray.array("u", ["a", "b", "c", "d"])

print(arr.typecode)
print(arr1.typecode)
print(arr2.typecode)

print(arr)
print(arr1)
print(arr2)





print(len(arr))
print(len(arr1))
print(len(arr2))

for i in range(0,len(arr)):
  print(arr[i], end=" ")
print("\n")
for i in range(0,len(arr1)):
  print(arr1[i], end=" ")
print("\n")
for i in range(0,len(arr2)):
    print(arr2[i], end=" ")

arr= myarray.array("i", [1,2,3])
for i in range(0, len(arr)):
 print(arr[i], end=" ")
print(end="\n")
arr.append(0)
arr.append(7)

arr.insert(19,31)

for i in range(0,len(arr)):
 print(arr[i], end=" ")
print("\n")

arr.pop(3)
for i in range(0,len(arr)):
  print(arr[i], end=" ")